import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SearchInputBox from "../../app/components/searchInputBox";
import Button from "../../app/components/button";
import HeaderComponent from "../components/header";
import LeftSideBar from "../components/leftSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const handleLeftSideSection = ()=>{
    console.log("handleLeftSideSection")
  }

  return (
    <div className="h-screen overflow-y-auto bg-[#121212] text-white">
      <HeaderComponent />
      <div className="flex min-h-[calc(100vh-66px)] sm:min-h-[calc(100vh-82px)]">
        <LeftSideBar 
        />
        {children}
      </div>
    </div>
  );
}
