export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import StoreProvider from "./storeProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
